# Generated by Django 5.0.6 on 2024-07-01 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_remove_status_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='alternate_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Alt_Number'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_joined'),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date_Of_Birth'),
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='department'),
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(blank=True, null=True, verbose_name='active_status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='job_role',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job_role'),
        ),
        migrations.AddField(
            model_name='employee',
            name='leave_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.status'),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Phone_Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First_Name'),
        ),
    ]
